### ISSUE TITLE
[SERVER] #3 Login

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/solidarite_assignment_server#3]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] 존재하지 않는 이메일이거나, 비밀번호가 틀렸을 경우 에러처리
2. [x] 이메일과 비밀번호로 로그인을 한다.
2. [x] 이메일과 비밀번호를 일치하면 해당 유저의 JWT 토큰을 발행한다.
3. [x] Response 값의 user 객체에는 비밀번호 필드를 포함시키지 않는다.

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
