### ISSUE TITLE
[SERVER] #5 SearchPosts

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/solidarite_assignment_server#5]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 게시물 리스트 조회

### TODO
1. [x] 생성된 게시물 리스트로 가지고 오기.
2. [x] 게시물이 없으면 빈 배열 반환
3. [x] Response의 user 객체의 경우 게시물을 작성한 닉네임만 가지고 오기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency: `High`, `Middle`, `Low`
