### ISSUE TITLE
[SERVER] #6 ReadPosts

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/solidarite_assignment_server#6]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 특정 게시물 가지고 오기

### TODO
1. [ ] 해당 id를 가진 게시물을 반환
2. [ ] 만일 로그인했고, 해당 유저가 게시물에 좋아요를 눌렀을 경우 isLike는 true 값을 가진다.
3. [ ] 로그인을 하지 않았거나, 로그인 했어도 좋아요를 누르지 않았을 경우 isLike는 false 값을 가진다.

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency:  `Middle`
