### ISSUE TITLE
[SERVER] #8 LikePost

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/solidarite_assignment_server#8]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 게시물에 좋아요 누르는 기능

### TODO
1. [ ] 좋아요가 눌린 게시물의 객체를 반환 
2. [ ] 좋아요 누름.
        - 중복 카운트하지 않음.
        - 좋아요 취소는 존재하지 않음
3. [ ] 로그인 and 유저가 게시물 좋아요를 눌렀으면 isLike는 true 값을
4. [ ] 로그인 X or 유저가 게시물에 좋아요를 누르지 않았으면 isLike는 true 값을

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency: `High`
